spring:
  mail:
    host: smtp.163.com
    username: 19357519363@163.com
    password: HTeZsrnyVCjxC2U6
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  application:
    name: service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stf6?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://47.110.248.94:3306/stf6?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: stf6
#    password: cxSeJMapipBCbSwx
    username: root
    password: 1908218002zjl

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1908218002zjl
mail:
  from:
    addr: 19357519363@163.com
sky:
  jwt:
    # ??jwt??????????
    admin-secret-key: arbiterarbiterarbiterarbiterarbiterarbiter
    # ??jwt????
    admin-ttl: 7200000
    # ?????????????
    admin-token-name: Authorization
logging:
  file:
#    name: /www/wwwroot/java/log/app-log.log
    name: /logs
upload:
  path: D:\\vue-project\\imgs  # ??????? ? nginx.conf ????
#  path: /www/wwwroot/img  # ??????? ? nginx.conf ????
#  reUrl: http://47.110.248.94:888 # nginx???ip??? ? nginx.conf ????
  reUrl: http://localhost:80 # nginx???ip??? ? nginx.conf ????